tasks:
  - init: pip3 install -r requirements.txt
    command: python3 src/app.py
ports:
  - port: 8080
    name: "Backend Server"
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - ms-python.python